language: python
branches:
  except:
    - legacy
    - experimental
env:
    - DB_URL=postgresql://postgres@localhost/
    - TOXENV=py27
    - TOXENV=py34
before_install: 
    - pip install tox
script: 
    - tox
addons:
  postgresql: "9.3"
