language: python
python:
    - 2.7
    - 3.3
    - 3.4
install:
    - pip install -r requirements.txt
    - pip install -e '.[test]'
addons:
    postgresql: "9.3"
script:
    py.test -v --cov-report=term-missing --cov=webcore -s {posargs}
after_success:
    coveralls